#include "ext.h"

const char* OBJECT_KIND_STR[] = {
    "EXT_OBJECT_KIND_GLOBAL_SCOPE",
    "EXT_OBJECT_KIND_VARIABLE",
    "EXT_OBJECT_KIND_FUNCTION",
    "EXT_OBJECT_KIND_CLASS",
    "EXT_OBJECT_KIND_STRUCT",
    "EXT_OBJECT_KIND_PARAMETER",
    "EXT_OBJECT_KIND_RETURN_VALUE",
    "EXT_OBJECT_KIND_GENERIC_PARAMETER",
    "EXT_OBJECT_KIND_TYPE"
};